.travis.yml: Update to modern Ruby versions
1.9.3 is old and [Travis fails for
it](https://travis-ci.org/dlokesh/1pass/builds/145591056) with
`NoMethodError: undefined method `spec' for nil:NilClass`.

https://github.com/jackc/tod/issues/36 says that dropping old Ruby
versions fixed this issue for them.